import type { Metadata } from "next";
import {Lora,Montserrat  } from "next/font/google"; 
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const lora = Lora ({
  variable: "--font-lora",
  weight: ["700"],
});

const montserrat = Montserrat ({
  variable: "--font-montserrat",
  weight: ["700"],
});     

export const metadata: Metadata = {
  title: "Nior",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${lora.variable} ${montserrat.variable}   antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}